name: money_assistant
description: A new Flutter project.

publish_to: 'none' # remove if you want to publish

version: 1.0.9

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  intl: ^0.20.2
  provider: ^6.1.5+1  
  flutter_screenutil: ^5.9.3

  # UI & UX
  flutter_screen_lock: ^9.2.2+2
  flutter_app_lock: ^4.3.0
  google_fonts: ^6.3.2
  table_calendar: ^3.2.0
  syncfusion_flutter_charts: ^31.1.22
  day_night_time_picker: ^1.3.1
  flutter_material_pickers: ^3.7.0
  sliding_up_panel: ^2.0.0+1
  keyboard_actions: ^4.2.0
  fluttertoast: ^9.0.0
  flutter_swipe_action_cell: ^3.1.6

  # Icons
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.10.0
  outline_material_icons: ^1.0.0
  flutter_boxicons: ^3.2.0
  icofont_flutter: ^1.4.0
  cupertino_icons: ^1.0.8

  # Device APIs
  local_auth: ^2.3.0
  permission_handler: ^12.0.1
  file_picker: ^10.3.3
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.0

dependency_overrides:
  flutter_colorpicker: ^1.1.0
  file_picker: ^10.3.3
  intl: ^0.20.2
  path: 1.9.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  
  # mocktail: ^1.0.4

flutter_native_splash:
  color: "#ffffff"
  image: images/splash_screen.jpeg
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/project/localization/lang/
    - images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/splash_screen.jpeg"
  min_sdk_android: 21
